/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#005236',
        'tertiary-container': '#271901',
        'on-tertiary-fixed': '#271901',
        'inverse-surface': '#213145',
        'primary-container': '#131b2e',
        'on-surface': '#0b1c30',
        'surface-tint': '#565e74',
        'inverse-primary': '#bec6e0',
        tertiary: '#000000',
        'surface-dim': '#cbdbf5',
        'tertiary-fixed': '#fcdeb5',
        surface: '#f8f9ff',
        secondary: '#006c49',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'on-surface-variant': '#45464d',
        'on-secondary-container': '#00714d',
        'tertiary-fixed-dim': '#dec29a',
        'inverse-on-surface': '#eaf1ff',
        'on-background': '#0b1c30',
        'secondary-container': '#6cf8bb',
        outline: '#76777d',
        'on-primary-fixed': '#131b2e',
        'surface-container-highest': '#d3e4fe',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#7c839b',
        'surface-bright': '#f8f9ff',
        'on-primary': '#ffffff',
        'surface-container-low': '#eff4ff',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#bec6e0',
        'on-tertiary-fixed-variant': '#574425',
        primary: '#000000',
        background: '#f8f9ff',
        'surface-container': '#e5eeff',
        'on-secondary-fixed': '#002113',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c6c6cd',
        'surface-container-high': '#dce9ff',
        'on-tertiary-container': '#98805d',
        'surface-variant': '#d3e4fe',
        'primary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#4edea3',
        'on-primary-fixed-variant': '#3f465c',
        'secondary-fixed': '#6ffbbe',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'base': '8px',
        'md': '16px',
        'gutter': '16px',
        'lg': '24px',
        'xl': '40px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'body-sm': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'mono-data': ['"Geist"', 'monospace'],
        'label-caps': ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg-mob': ['24px', { lineHeight: '32px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'mono-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
      },
    },
  },
  plugins: [],
}
